on:
  push:
  pull_request:

jobs:
  cmake:
    runs-on: ubuntu-latest
    container: fedora:40
    steps:
      - run: |
          dnf install -y git
          dnf groupinstall -y "Development Tools" "Development Libraries"
          dnf install -y cmake extra-cmake-modules kf6-kirigami2-devel kf6-ki18n-devel kf6-kcoreaddons-devel kf6-kiconthemes-devel qt6-qtbase-devel qt6-qtdeclarative-devel qt6-qtquickcontrols2-devel qqc2-desktop-style
      - uses: actions/checkout@v4
      - run: |
          cmake -B build
          cmake --build ./build
