on:
  push:
  pull_request:

jobs:
  cmake:
    runs-on: ubuntu-latest
    container: ghcr.io/lecrisut/dev-env:main
    steps:
      - run: |
          sudo dnf install -y git
          sudo dnf groupinstall -y "Development Tools" "Development Libraries"
          sudo dnf install -y cmake extra-cmake-modules kf6-kirigami2-devel kf6-ki18n-devel kf6-kcoreaddons-devel kf6-kiconthemes-devel qt6-qtbase-devel qt6-qtdeclarative-devel qt6-qtquickcontrols2-devel kf6-qqc2-desktop-style
      - uses: actions/checkout@v4
      - run: |
          cmake -B build
          cmake --build ./build
